# Generated by Django 6.0.2 on 2026-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен')),
                ('isAdmin', models.BooleanField(default=True, verbose_name='Администратор')),
                ('isInspector', models.BooleanField(default=False, verbose_name='Инспектор')),
            ],
            options={
                'verbose_name': 'администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('isInspector', models.BooleanField(default=True, verbose_name='Инспектор')),
            ],
            options={
                'verbose_name': 'инспектор',
                'verbose_name_plural': 'Инспекторы',
            },
        ),
    ]
