# Generated by Django 6.0.2 on 2026-02-14 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportData', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Паспорт должен быть в формате: 1234 567890', regex='^\\d{4}\\s?\\d{6}$')], verbose_name='Серия и номер паспорта')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567'", regex='^\\+?7?\\d{10,15}$')], verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('role', models.CharField(choices=[('worker', 'Сотрудник'), ('lead', 'Старший сотрудник')], max_length=10, verbose_name='Роль')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('isActive', models.BooleanField(default=False, verbose_name='Уволен или работает')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('isInspector', models.BooleanField(default=False, verbose_name='Инспектор')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
