# Generated by Django 6.0.2 on 2026-02-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('employeesNeeded', models.IntegerField(verbose_name='Требуется сотрудников')),
                ('employeesReady', models.BooleanField(default=False, verbose_name='Укомплектовано')),
                ('payment', models.IntegerField(verbose_name='Оплата')),
                ('time', models.DateTimeField(verbose_name='Время проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employees', models.ManyToManyField(blank=True, related_name='works', to='main_page.user', verbose_name='Сотрудники')),
                ('leadEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_works', to='main_page.user', verbose_name='Старший сотрудник')),
            ],
            options={
                'verbose_name': 'заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
            },
        ),
    ]
