# Generated by Django 6.0.2 on 2026-02-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_workobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkObject',
        ),
    ]
