# Generated by Django 6.0.2 on 2026-02-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.JSONField(blank=True, default=list, verbose_name='Список аттестаций'),
        ),
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.JSONField(blank=True, default=list, verbose_name='Список документов'),
        ),
        migrations.AddField(
            model_name='user',
            name='noCertifications',
            field=models.BooleanField(default=True, verbose_name='Нет непройденных аттестаций'),
        ),
        migrations.AddField(
            model_name='user',
            name='noDocuments',
            field=models.BooleanField(default=True, verbose_name='Неподписанные документы'),
        ),
    ]
