# Generated by Django 6.0.2 on 2026-02-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_user_certifications_user_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='noCertifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='noDocuments',
        ),
    ]
