# Generated by Django 6.0.2 on 2026-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_remove_user_nocertifications_remove_user_nodocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_certifications',
            field=models.JSONField(blank=True, default=list, help_text='ID тестов, которые нужно пройти', verbose_name='Назначенные аттестации'),
        ),
    ]
