# Generated by Django 5.2.12 on 2026-03-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_admin_id_alter_inspector_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название участка')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код участка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_global_admin',
            field=models.BooleanField(default=False, verbose_name='Глобальный администратор'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Работает'), ('suspended', 'Отстранен'), ('sick_leave', 'На больничном'), ('dismissed', 'Уволен')], default='pending', max_length=20, verbose_name='Статус трудоустройства'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='main_page.user', verbose_name='Непосредственный начальник'),
        ),
        migrations.AddField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Начальник участка'), ('medic', 'Медработник'), ('inspector', 'Инспектор'), ('global_admin', 'Глобальный администратор')], default='employee', max_length=20, verbose_name='Системная роль'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_admins', to='main_page.department', verbose_name='Закрепленный участок'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspectors', to='main_page.department', verbose_name='Закрепленный участок'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='main_page.department', verbose_name='Участок'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Должность')),
                ('is_managerial', models.BooleanField(default=False, verbose_name='Руководящая')),
                ('requires_medical_check', models.BooleanField(default=True, verbose_name='Требует медосмотра')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main_page.department', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='main_page.position', verbose_name='Должность'),
        ),
    ]
