# Generated by Django 5.2.12 on 2026-04-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_department_admin_full_name_admin_is_global_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Начальник участка')], default='employee', max_length=20, verbose_name='Системная роль'),
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен')),
                ('isAdmin', models.BooleanField(verbose_name='Администратор')),
                ('isInspector', models.BooleanField(verbose_name='Инспектор')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medics', to='main_page.department', verbose_name='Закрепленный участок')),
            ],
            options={
                'verbose_name': 'медработник',
                'verbose_name_plural': 'Медработники',
            },
        ),
    ]
