# Generated by Django 6.0.2 on 2026-02-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0007_remove_user_nocertifications_remove_user_nodocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to='main_page.admin', verbose_name='Создал (админ)')),
                ('created_by_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to='main_page.inspector', verbose_name='Создал (инспектор)')),
            ],
            options={
                'verbose_name': 'тест аттестации',
                'verbose_name_plural': 'Тесты аттестации',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку с вопросом', null=True, upload_to='questions/', verbose_name='Картинка вопроса')),
                ('correct_answer', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], help_text='Выберите правильный ответ: Да или Нет', verbose_name='Правильный ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='profiles.certificationtest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Заблокирован')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('reason', models.CharField(default='Проваленная аттестация', max_length=255, verbose_name='Причина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main_page.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'блокировка',
                'verbose_name_plural': 'Блокировки',
            },
        ),
        migrations.CreateModel(
            name='UserTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('passed', models.BooleanField(default=False, verbose_name='Сдал?')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='profiles.certificationtest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='main_page.user', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiles.usertestattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='WorkObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('employeesNeeded', models.IntegerField(verbose_name='Требуется сотрудников')),
                ('employeesReady', models.BooleanField(default=False, verbose_name='Укомплектовано')),
                ('payment', models.IntegerField(verbose_name='Оплата')),
                ('time', models.DateTimeField(verbose_name='Время проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_signup_time', models.DateTimeField(auto_now=True, verbose_name='Последняя запись')),
                ('employees', models.ManyToManyField(blank=True, related_name='works', to='main_page.user', verbose_name='Сотрудники')),
                ('leadEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_works', to='main_page.user', verbose_name='Старший сотрудник')),
            ],
            options={
                'verbose_name': 'заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
            },
        ),
    ]
