# Generated by Django 6.0.2 on 2026-02-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='', help_text='Введите текст вопроса', verbose_name='Текст вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Можно добавить картинку к вопросу', null=True, upload_to='questions/', verbose_name='Картинка (необязательно)'),
        ),
    ]
