# Generated by Django 6.0.2 on 2026-02-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_remove_user_nocertifications_remove_user_nodocuments'),
        ('profiles', '0002_question_text_alter_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workobject',
            options={'ordering': ['-time'], 'verbose_name': 'Заказ-наряд', 'verbose_name_plural': 'Заказ-наряды'},
        ),
        migrations.RemoveField(
            model_name='workobject',
            name='last_signup_time',
        ),
        migrations.AddField(
            model_name='workobject',
            name='status',
            field=models.CharField(choices=[('recruiting', 'Набор сотрудников'), ('completed', 'Завершен')], default='recruiting', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='works', to='main_page.user', verbose_name='Записанные сотрудники'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='employeesNeeded',
            field=models.IntegerField(default=1, verbose_name='Требуется сотрудников'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='employeesReady',
            field=models.BooleanField(default=False, verbose_name='Укомплектован'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='leadEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_works', to='main_page.user', verbose_name='Старший сотрудник'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='time',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
    ]
