# Generated by Django 6.0.2 on 2026-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_workobject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default=1, help_text='Первый вариант ответа', max_length=200, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default=1, help_text='Второй вариант ответа', max_length=200, verbose_name='Вариант 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default=1, help_text='Третий вариант ответа', max_length=200, verbose_name='Вариант 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Вариант 1'), (2, 'Вариант 2'), (3, 'Вариант 3')], help_text='Выберите номер правильного ответа', verbose_name='Правильный ответ'),
        ),
    ]
