# Generated by Django 6.0.2 on 2026-03-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_question_image_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workobject',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='Продолжительность (часы)'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='last_signup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя запись'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='status',
            field=models.CharField(choices=[('recruiting', 'Набор сотрудников'), ('waiting', 'Ожидание'), ('completed', 'Завершен')], default='recruiting', max_length=20, verbose_name='Статус'),
        ),
    ]
