# Generated by Django 6.0.2 on 2026-03-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_user_assigned_certifications'),
        ('profiles', '0006_document_documentsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_number', models.CharField(max_length=50, verbose_name='Номер объекта')),
                ('video', models.FileField(upload_to='inspections/videos/', verbose_name='Видео')),
                ('check_helmet', models.BooleanField(default=True, verbose_name='Проверять каски')),
                ('check_mask', models.BooleanField(default=False, verbose_name='Проверять маски')),
                ('violation_seconds', models.FloatField(default=3.0, verbose_name='Порог нарушения (сек)')),
                ('frame_stride', models.PositiveIntegerField(default=1, verbose_name='Шаг по кадрам')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=20, verbose_name='Статус')),
                ('error', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт обработки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание обработки')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.inspector', verbose_name='Инспектор')),
            ],
            options={
                'verbose_name': 'Проверка видео (СИЗ)',
                'verbose_name_plural': 'Проверки видео (СИЗ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('timestamp_sec', models.FloatField(default=0.0, verbose_name='Время (сек)')),
                ('frame_index', models.IntegerField(default=0, verbose_name='Кадр')),
                ('person_track_id', models.IntegerField(default=0, verbose_name='ID человека (трек)')),
                ('violation_type', models.CharField(choices=[('no_helmet', 'Нет каски'), ('no_mask', 'Нет маски'), ('no_helmet_no_mask', 'Нет каски и маски')], max_length=30, verbose_name='Тип нарушения')),
                ('conf_helmet', models.FloatField(blank=True, null=True, verbose_name='Уверенность (каска)')),
                ('conf_mask', models.FloatField(blank=True, null=True, verbose_name='Уверенность (маска)')),
                ('image', models.ImageField(upload_to='inspections/screenshots/', verbose_name='Скриншот')),
                ('confirmed', models.BooleanField(blank=True, null=True, verbose_name='Подтверждено?')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий инспектора')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='profiles.videoinspection', verbose_name='Проверка')),
            ],
            options={
                'verbose_name': 'Нарушение (скриншот)',
                'verbose_name_plural': 'Нарушения (скриншоты)',
                'ordering': ['-created_at'],
            },
        ),
    ]
