# Generated by Django 5.2.12 on 2026-03-24 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_department_admin_full_name_admin_is_global_admin_and_more'),
        ('profiles', '0009_alter_certificationtest_id_alter_document_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Тип нарушения')),
                ('category', models.CharField(choices=[('medical', 'Медосмотр'), ('work_order', 'Наряд'), ('ppe', 'СИЗ'), ('discipline', 'Дисциплина')], max_length=20, verbose_name='Категория')),
                ('severity', models.CharField(choices=[('low', 'Легкое'), ('medium', 'Среднее'), ('high', 'Тяжелое'), ('critical', 'Критическое')], max_length=20, verbose_name='Тяжесть')),
                ('default_sanction', models.CharField(choices=[('warning', 'Предупреждение'), ('explanation', 'Объяснительная'), ('fine', 'Штраф / лишение премии'), ('suspension', 'Отстранение'), ('dismissal_notice', 'Уведомление на увольнение')], default='warning', max_length=30, verbose_name='Базовая санкция')),
                ('default_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'тип нарушения',
                'verbose_name_plural': 'Типы нарушений',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workobject',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='completion_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий по закрытию'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_objects', to='main_page.department', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание задания'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='extended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Продлено до'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='extension_reason',
            field=models.TextField(blank=True, verbose_name='Причина продления'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='planned_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Плановое окончание'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='responsible_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_work_objects', to='main_page.admin', verbose_name='Ответственный руководитель'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='work_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='Вид работ'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='zone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Зона выполнения работ'),
        ),
        migrations.AlterField(
            model_name='certificationtest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videoinspection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('recruiting', 'Набор сотрудников'), ('waiting', 'Ожидание начала'), ('in_progress', 'В работе'), ('paused', 'На паузе'), ('extended', 'Продлен'), ('completed', 'Завершен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название камеры')),
                ('zone', models.CharField(blank=True, max_length=150, verbose_name='Зона / локация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='main_page.department', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='videoinspection',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='profiles.camera', verbose_name='Камера'),
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='main_page.user', verbose_name='Сотрудник')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sick_leaves', to='main_page.user', verbose_name='Выдал')),
            ],
            options={
                'verbose_name': 'больничный',
                'verbose_name_plural': 'Больничные',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('warning', 'Предупреждение'), ('explanation', 'Объяснительная'), ('fine', 'Лишение премии / штраф'), ('suspension', 'Отстранение'), ('dismissal_notice', 'Уведомление на увольнение')], max_length=30, verbose_name='Вид санкции')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Размер удержания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус')),
                ('starts_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sanctions', to='main_page.admin', verbose_name='Назначил администратор')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='main_page.user', verbose_name='Сотрудник')),
                ('work_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions', to='profiles.workobject', verbose_name='Наряд')),
                ('violation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions', to='profiles.violationtype', verbose_name='Основание')),
            ],
            options={
                'verbose_name': 'санкция',
                'verbose_name_plural': 'Санкции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('morning', 'Утренний осмотр'), ('evening', 'Вечерний осмотр')], max_length=20, verbose_name='Тип осмотра')),
                ('check_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата осмотра')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отметки')),
                ('decision', models.CharField(choices=[('fit', 'Допущен'), ('restricted', 'Допущен с ограничениями'), ('unfit', 'Не допущен')], max_length=20, verbose_name='Решение')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='Давление')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура')),
                ('pulse', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пульс')),
                ('complaints', models.TextField(blank=True, verbose_name='Жалобы')),
                ('alcohol_free', models.BooleanField(default=True, verbose_name='Трезв')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий медика')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checks', to='main_page.user', verbose_name='Сотрудник')),
                ('medic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_medical_checks', to='main_page.user', verbose_name='Медработник')),
            ],
            options={
                'verbose_name': 'медицинский осмотр',
                'verbose_name_plural': 'Медицинские осмотры',
                'ordering': ['-checked_at'],
                'unique_together': {('employee', 'check_type', 'check_date')},
            },
        ),
    ]
