# Generated by Django 5.2.12 on 2026-04-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_alter_user_system_role_medic'),
        ('profiles', '0011_certificationtest_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcheck',
            name='medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_checks', to='main_page.medic', verbose_name='Медработник'),
        ),
    ]
