from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    # Пути пользователя
    path('user/documents/', views.user_documents, name='user_documents'),
    path('user/documents/<int:doc_id>/', views.view_document, name='view_document'),
    path('user/documents/<int:doc_id>/sign/', views.sign_document, name='sign_document'),
    path('user/works/<int:work_id>/unsubscribe/', views.user_unsubscribe_work, name='user_unsubscribe_work'),
    path('user/works/available/', views.user_available_works, name='user_available_works'),
    path('user/works/my/', views.user_current_works, name='user_current_works'),
    path('user/works/<int:work_id>/signup/', views.user_signup_work, name='user_signup_work'),
    path('user/tests/', views.user_test_list, name='user_test_list'),
    path('user/tests/<int:test_id>/take/', views.user_take_test, name='user_take_test'),
    path('user/tests/history/', views.user_test_history, name='user_test_history'),
    path('user/violations/', views.user_violations, name='user_violations'),
    path('user/ppe-violations/', views.user_ppe_violations, name='user_ppe_violations'),
    # Пути администратора
    path('admin/users/', views.admin_users_list, name='admin_users_list'),
    path('admin/users/confirm/', views.confirm_users, name='confirm_users'),
    path('admin/user/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/user/<int:user_id>/confirm/', views.admin_user_confirm, name='admin_user_confirm'),
    path('admin/tests/', views.admin_test_list, name='admin_test_list'),
    path('admin/tests/create/', views.admin_test_create, name='admin_test_create'),
    path('admin/tests/<int:test_id>/edit/', views.admin_test_edit, name='admin_test_edit'),
    path('admin/tests/<int:test_id>/delete/', views.admin_test_delete, name='admin_test_delete'),
    path('admin/tests/<int:test_id>/results/', views.admin_test_results, name='admin_test_results'),
    path('admin/workobjects/', views.admin_workobjects_list, name='admin_workobjects_list'),
    path('admin/workobjects/create/', views.admin_workobject_create, name='admin_workobject_create'),
    path('admin/workobjects/<int:pk>/edit/', views.admin_workobject_edit, name='admin_workobject_edit'),
    path('admin/workobjects/<int:pk>/delete/', views.admin_workobject_delete, name='admin_workobject_delete'),
    path('admin/workobjects/<int:pk>/assign-lead/', views.admin_workobject_assign_lead, name='admin_workobject_assign_lead'),
    path('admin/assign-all-tests/', views.admin_assign_all_tests_to_all_users, name='admin_assign_all_tests'),
    path('admin/documents/', views.admin_document_list, name='admin_document_list'),
    path('admin/documents/create/', views.admin_document_create, name='admin_document_create'),
    path('admin/medical-checks/', views.admin_medical_checks_list, name='admin_medical_checks_list'),
    path('admin/medical-checks/create/', views.admin_medical_check_create, name='admin_medical_check_create'),
    path('admin/sick-leaves/', views.admin_sick_leaves_list, name='admin_sick_leaves_list'),
    path('admin/sick-leaves/create/', views.admin_sick_leave_create, name='admin_sick_leave_create'),
    path('admin/sanctions/', views.admin_sanctions_list, name='admin_sanctions_list'),
    path('admin/sanctions/create/', views.admin_sanction_create, name='admin_sanction_create'),
    # Инспектор: проверка СИЗ по видео
    path('inspector/video/', views.inspector_video_inspections, name='inspector_video_inspections'),
    path('inspector/video/new/', views.inspector_video_inspection_create, name='inspector_video_inspection_create'),
    path('inspector/video/<int:pk>/', views.inspector_video_inspection_detail, name='inspector_video_inspection_detail'),
    path('inspector/video/<int:pk>/violation/<int:violation_id>/', views.inspector_violation_decision, name='inspector_violation_decision'),
    path('medic/employees/', views.medic_employees_list, name='medic_employees_list'),
    path('medic/medical-checks/', views.medic_medical_checks_list, name='medic_medical_checks_list'),
    path('medic/medical-checks/create/', views.medic_medical_check_create, name='medic_medical_check_create'),
    path('medic/sick-leaves/', views.medic_sick_leaves_list, name='medic_sick_leaves_list'),
    path('medic/sick-leaves/create/', views.medic_sick_leave_create, name='medic_sick_leave_create'),
    path('medic/medical-checks/create/<int:employee_id>/', views.medic_medical_check_create_for_employee, name='medic_medical_check_create_for_employee'),
    path('medic/medical-checks/<int:check_id>/', views.medic_medical_check_detail, name='medic_medical_check_detail'),
    path('medic/sick-leaves/create/<int:employee_id>/', views.medic_sick_leave_create_for_employee, name='medic_sick_leave_create_for_employee'),
]
